/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ploximo.Views;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ploximo.controle.JogoController;
import ploximo.controle.Pontuacao;
import ploximo.controle.SerializacaoDaPontuacao;
/**
 *
 * @author Bianca
 */
public class FimDoDia extends javax.swing.JFrame {
    JogoController jogoController = new JogoController();
    Pontuacao pontos = new Pontuacao();
    boolean salvou = false;
    /**
     * Creates new form FimDoDia
     */
    public FimDoDia(Pontuacao pt) {
        initComponents();
        
        this.pontos = pt;
        
        ArrayList botoes = new ArrayList<>();
        botoes.add(menuBotao);
        botoes.add(continuarBotao);
        botoes.add(salvarBotao);
        botoes.add(pontuacaoBotao);
        jogoController.configurarBotoes(botoes);
        jogoController.iniciarMeusComponentes(this, fundo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salvarBotao = new javax.swing.JButton();
        continuarBotao = new javax.swing.JButton();
        menuBotao = new javax.swing.JButton();
        pontuacaoBotao = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        salvarBotao.setContentAreaFilled(false);
        salvarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(salvarBotao);
        salvarBotao.setBounds(40, 240, 140, 50);

        continuarBotao.setContentAreaFilled(false);
        continuarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(continuarBotao);
        continuarBotao.setBounds(30, 340, 200, 50);

        menuBotao.setContentAreaFilled(false);
        menuBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(menuBotao);
        menuBotao.setBounds(1030, 240, 120, 50);

        pontuacaoBotao.setContentAreaFilled(false);
        pontuacaoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontuacaoBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(pontuacaoBotao);
        pontuacaoBotao.setBounds(950, 340, 210, 50);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ploximo/Imagens/fimdodia.png"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 1200, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBotaoActionPerformed
        System.out.println("salvar");
        //novo para o xml appendable
        try {
            // TODO add your handling code here:
            pontos.armazenar();
        } catch (IOException ex) {
            Logger.getLogger(FimDoDia.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Erro de XML.");
        }
        //Pontuacao[] serie = {this.pontos};
        salvou = true;
        // TODO add your handling code here:
        
        Pontuacao[] serie = {this.pontos};
        SerializacaoDaPontuacao serialpontos = new SerializacaoDaPontuacao();
        ArrayList<Pontuacao> ob = null;
        try {
            System.out.println("ainda não montou o vetor");
             ob = serialpontos.montarVetor("score.txt");
             System.out.println("Montou o vetor");
        } catch (IOException ex) {
            Logger.getLogger(FimDoDia.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        Pontuacao [] p = new Pontuacao[ob.size()];
        for(int i = 0; i < ob.size();i++){
         p[i] = ob.get(i);
         System.out.println("p[i] = " + p[i].getNome());
         System.out.println("ob[i] = " + ob.get(i).getNome());
        }
        System.out.println("ainda não serializou");
        serialpontos.serializar(p);
        System.out.println("serializou");
        serialpontos.LerSerialização();
    }//GEN-LAST:event_salvarBotaoActionPerformed

    private void continuarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarBotaoActionPerformed
        Pontuacao p = new Pontuacao();
        if (!salvou) {
            Object[] opcoes = {"Salvar e continuar", "Apenas continuar"};

        int n = JOptionPane.showOptionDialog(null,
            "Deseja salvar?",
            "",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opcoes,
            opcoes[0]);

        if (opcoes[n].equals(opcoes[0])) {
            System.out.println("salvou");
            Pontuacao[] serie = {this.pontos};
            SerializacaoDaPontuacao serialpontos = new SerializacaoDaPontuacao();
            serialpontos.serializar(serie);
            serialpontos.LerSerialização();
        }
        
        }
        

        jogoController.trocarDeTela(this, new JogoTela(p));

    }//GEN-LAST:event_continuarBotaoActionPerformed

    private void menuBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBotaoActionPerformed
        jogoController.trocarDeTela(this, new MenuPrincipal());

    }//GEN-LAST:event_menuBotaoActionPerformed

    private void pontuacaoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontuacaoBotaoActionPerformed
        jogoController.trocarDeTela(this, new HighScores());
    }//GEN-LAST:event_pontuacaoBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FimDoDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FimDoDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FimDoDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FimDoDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pontuacao ponto = new Pontuacao();
                new FimDoDia(ponto).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuarBotao;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton menuBotao;
    private javax.swing.JButton pontuacaoBotao;
    private javax.swing.JButton salvarBotao;
    // End of variables declaration//GEN-END:variables
}
