/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ploximo.Views;
import java.awt.Font;
import java.util.ArrayList;
import java.util.EventObject;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import ploximo.controle.JogoController;
import ploximo.controle.SerializacaoDaPontuacao;

/**
 *
 * @author Bianca
 */
public class HighScores extends javax.swing.JFrame {

    JogoController jogoController = new JogoController();
    /**
     * Creates new form HighScores
     */
    public HighScores() {
        initComponents();
        ArrayList botoes = new ArrayList();
        botoes.add(menuBotao);
        jogoController.configurarBotoes(botoes);
        
        //jTextArea1 = new JTextArea(); 
        SerializacaoDaPontuacao sp = new SerializacaoDaPontuacao();
        String [][] matriz = sp.LerSerialização();
        
        
        
        this.setSize(fundo.getWidth(), fundo.getHeight() + 28);
       highScoresTabela.setRowHeight(30);
       highScoresTabela.getTableHeader().setFont(new Font("PixelPlay", Font.BOLD, 18));
       
       for(int i = 0;i<10;i++){
           highScoresTabela.setValueAt((Object) matriz[i][0], i, 0);
           highScoresTabela.setValueAt((Object) matriz[i][1].replaceAll("null",""), i, 1);
       }
       
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        highScoresTabela = new javax.swing.JTable();
        menuBotao = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        highScoresTabela.setBackground(new java.awt.Color(204, 204, 204));
        highScoresTabela.setFont(new java.awt.Font("PixelPlay", 0, 18)); // NOI18N
        highScoresTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        highScoresTabela.setAutoscrolls(false);
        highScoresTabela.setFocusable(false);
        highScoresTabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(highScoresTabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(510, 220, 210, 160);

        menuBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(menuBotao);
        menuBotao.setBounds(550, 510, 120, 40);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ploximo/Imagens/highscores.png"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 1200, 675);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBotaoActionPerformed
        jogoController.trocarDeTela(this, new MenuPrincipal());
    }//GEN-LAST:event_menuBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HighScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HighScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HighScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HighScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HighScores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JTable highScoresTabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menuBotao;
    // End of variables declaration//GEN-END:variables
}
