/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ploximo.Views;

import java.awt.Container;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import ploximo.Models.Cronometro;
import ploximo.Models.Pessoa;
import ploximo.controle.Data;
import ploximo.controle.JogoController;
import ploximo.controle.PessoaController;
import ploximo.controle.Pontuacao;

/**
 *
 * @author Luan
 */
public class JogoTela extends javax.swing.JFrame { 
    
    Pessoa imigrante;
    
    JogoController jogoController = new JogoController();
    PessoaController pc = new PessoaController();
    boolean temPessoa = false;
    
    JButton botao1;
    JButton botao2;
    Pontuacao pontos = new Pontuacao();
    String[] regrasArray = {"Usuários devem apresentar identidade, passaporte e permissão de acesso.", "As informações listadas nos documentos devem estar de acordo entre si.", "Todos os documentos devem estar válidos.", "Não são permitidos armas ou contrabando."};
    
    public JogoTela(Pontuacao pontos) {
        initComponents();  
        ArrayList botoes = new ArrayList<>();
        this.pontos = pontos;
        
        dataBotao.setText(Data.gerarDataAtual());
        regra1.setText("<html>" + regrasArray[0] + "</html>");
        
        regra2.setText("<html>" + regrasArray[1] + "</html>");
        regra3.setText("<html>" + regrasArray[2] + "</html>");
        regra4.setText("<html>" + regrasArray[3] + "</html>");
                
        idFoto.setEnabled(false);
        passFoto.setEnabled(false);
        pessoaBotao.setEnabled(false);
        
        Cronometro cronometro = new Cronometro(this);
        cronometro.start();
        
        botoes.add(aprovarBotao);
        botoes.add(negarBotao);
        botoes.add(regrasMiniBotao);
        botoes.add(permMiniBotao);
        botoes.add(idMiniBotao);
        botoes.add(ploximoBotao);
        
        passMiniBotao.setVisible(false);
        idMiniBotao.setVisible(false);
        permMiniBotao.setVisible(false);
        pesoBotao.setVisible(false);

        jogoController.configurarBotoes(botoes);
        iniciarMeusComponentes();
        jogoController.togglePainel(idPainel);
        jogoController.togglePainel(passPainel);
        jogoController.togglePainel(permPainel);
        jogoController.togglePainel(regrasPainel);
        
        idPainel.setVisible(false);
        passPainel.setVisible(false);
        permPainel.setVisible(false);
        regrasPainel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regrasPainel = new javax.swing.JLayeredPane();
        regra1 = new javax.swing.JButton();
        regra2 = new javax.swing.JButton();
        regra3 = new javax.swing.JButton();
        regra4 = new javax.swing.JButton();
        regras = new javax.swing.JLabel();
        permPainel = new javax.swing.JLayeredPane();
        permPassCod = new javax.swing.JButton();
        permNacio = new javax.swing.JButton();
        permMotivo = new javax.swing.JButton();
        permAlt = new javax.swing.JButton();
        permDuracao = new javax.swing.JButton();
        permNome = new javax.swing.JButton();
        permVal = new javax.swing.JButton();
        permPeso = new javax.swing.JButton();
        permissao = new javax.swing.JLabel();
        passPainel = new javax.swing.JLayeredPane();
        passNome = new javax.swing.JButton();
        passFoto = new javax.swing.JButton();
        passSexo = new javax.swing.JButton();
        passNasc = new javax.swing.JButton();
        passPais = new javax.swing.JButton();
        passVal = new javax.swing.JButton();
        passCod = new javax.swing.JButton();
        passaporte = new javax.swing.JLabel();
        idPainel = new javax.swing.JLayeredPane();
        idNasc = new javax.swing.JButton();
        idAlt = new javax.swing.JButton();
        idFoto = new javax.swing.JButton();
        idPeso = new javax.swing.JButton();
        idNome = new javax.swing.JButton();
        identidade = new javax.swing.JLabel();
        pontuacaoLabel = new javax.swing.JLabel();
        cronometroLabel = new javax.swing.JLabel();
        scannear = new javax.swing.JButton();
        idMiniBotao = new javax.swing.JButton();
        permMiniBotao = new javax.swing.JButton();
        passMiniBotao = new javax.swing.JButton();
        regrasMiniBotao = new javax.swing.JButton();
        ploximoBotao = new javax.swing.JButton();
        pessoaBotao = new javax.swing.JButton();
        pesoBotao = new javax.swing.JButton();
        dataBotao = new javax.swing.JButton();
        aprovarBotao = new javax.swing.JButton();
        negarBotao = new javax.swing.JButton();
        ataqueLabel = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        regrasPainel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regra1.setBorderPainted(false);
        regra1.setContentAreaFilled(false);
        regra1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regra1.setName(""); // NOI18N
        regra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regra1ActionPerformed(evt);
            }
        });
        regrasPainel.add(regra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 210, 50));

        regra2.setBorderPainted(false);
        regra2.setContentAreaFilled(false);
        regra2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regrasPainel.add(regra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 210, 50));

        regra3.setBorderPainted(false);
        regra3.setContentAreaFilled(false);
        regra3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regra3ActionPerformed(evt);
            }
        });
        regrasPainel.add(regra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 210, 50));

        regra4.setBorderPainted(false);
        regra4.setContentAreaFilled(false);
        regra4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regrasPainel.add(regra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 210, 50));

        regras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ploximo/Imagens/regras.png"))); // NOI18N
        regrasPainel.add(regras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 380));

        getContentPane().add(regrasPainel);
        regrasPainel.setBounds(380, 270, 320, 400);

        permPainel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        permPassCod.setContentAreaFilled(false);
        permPassCod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        permPassCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permPassCodActionPerformed(evt);
            }
        });
        permPainel.add(permPassCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 80, 20));

        permNacio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        permNacio.setContentAreaFilled(false);
        permNacio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        permNacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permNacioActionPerformed(evt);
            }
        });
        permPainel.add(permNacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 20));

        permMotivo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        permMotivo.setContentAreaFilled(false);
        permMotivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        permMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permMotivoActionPerformed(evt);
            }
        });
        permPainel.add(permMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 20));

        permAlt.setContentAreaFilled(false);
        permAlt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        permAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permAltActionPerformed(evt);
            }
        });
        permPainel.add(permAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 20));

        permDuracao.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        permDuracao.setContentAreaFilled(false);
        permDuracao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        permDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permDuracaoActionPerformed(evt);
            }
        });
        permPainel.add(permDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 90, 20));

        permNome.setContentAreaFilled(false);
        permNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        permNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permNomeActionPerformed(evt);
            }
        });
        permPainel.add(permNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 20));

        permVal.setContentAreaFilled(false);
        permVal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        permVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permValActionPerformed(evt);
            }
        });
        permPainel.add(permVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 100, 20));

        permPeso.setContentAreaFilled(false);
        permPeso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        permPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permPesoActionPerformed(evt);
            }
        });
        permPainel.add(permPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 90, 20));

        permissao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ploximo/Imagens/Permissaopequena.png"))); // NOI18N
        permissao.setText("jLabel1");
        permPainel.add(permissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        getContentPane().add(permPainel);
        permPainel.setBounds(590, 270, 250, 320);

        passPainel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passNome.setContentAreaFilled(false);
        passNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        passNome.setMaximumSize(new java.awt.Dimension(250, 20));
        passNome.setMinimumSize(new java.awt.Dimension(250, 20));
        passNome.setPreferredSize(new java.awt.Dimension(250, 20));
        passNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passNomeActionPerformed(evt);
            }
        });
        passPainel.add(passNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 250, 20));

        passFoto.setContentAreaFilled(false);
        passFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        passFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFotoActionPerformed(evt);
            }
        });
        passPainel.add(passFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 100));

        passSexo.setContentAreaFilled(false);
        passSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        passSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passSexoActionPerformed(evt);
            }
        });
        passPainel.add(passSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 110, 20));

        passNasc.setContentAreaFilled(false);
        passNasc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        passNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passNascActionPerformed(evt);
            }
        });
        passPainel.add(passNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 110, 20));

        passPais.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        passPais.setContentAreaFilled(false);
        passPais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        passPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPaisActionPerformed(evt);
            }
        });
        passPainel.add(passPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 120, 20));

        passVal.setContentAreaFilled(false);
        passVal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        passVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passValActionPerformed(evt);
            }
        });
        passPainel.add(passVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 110, 20));

        passCod.setContentAreaFilled(false);
        passCod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        passCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passCodActionPerformed(evt);
            }
        });
        passPainel.add(passCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 140, 20));

        passaporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ploximo/Imagens/Passaportepequeno.png"))); // NOI18N
        passaporte.setText("jLabel1");
        passaporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passaporteMouseClicked(evt);
            }
        });
        passPainel.add(passaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, -1));

        getContentPane().add(passPainel);
        passPainel.setBounds(880, 230, 330, 330);

        idPainel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idNasc.setContentAreaFilled(false);
        idNasc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        idNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNascActionPerformed(evt);
            }
        });
        idPainel.add(idNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        idAlt.setContentAreaFilled(false);
        idAlt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        idAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAltActionPerformed(evt);
            }
        });
        idPainel.add(idAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        idFoto.setContentAreaFilled(false);
        idFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        idFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFotoActionPerformed(evt);
            }
        });
        idPainel.add(idFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 73, 80, 100));

        idPeso.setContentAreaFilled(false);
        idPeso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        idPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPesoActionPerformed(evt);
            }
        });
        idPainel.add(idPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        idNome.setContentAreaFilled(false);
        idNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        idNome.setMaximumSize(new java.awt.Dimension(190, 23));
        idNome.setMinimumSize(new java.awt.Dimension(190, 23));
        idNome.setPreferredSize(new java.awt.Dimension(190, 23));
        idNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNomeActionPerformed(evt);
            }
        });
        idPainel.add(idNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 190, -1));

        identidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ploximo/Imagens/Identidadepequena.png"))); // NOI18N
        idPainel.add(identidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 330, -1));

        getContentPane().add(idPainel);
        idPainel.setBounds(770, 470, 320, 220);

        pontuacaoLabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        pontuacaoLabel.setText("Pontuação: 0");
        getContentPane().add(pontuacaoLabel);
        pontuacaoLabel.setBounds(460, 10, 220, 30);

        cronometroLabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        cronometroLabel.setText("05:00");
        getContentPane().add(cronometroLabel);
        cronometroLabel.setBounds(1130, 10, 60, 30);

        scannear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        scannear.setText("Passar por scanner");
        scannear.setMaximumSize(new java.awt.Dimension(135, 23));
        scannear.setMinimumSize(new java.awt.Dimension(135, 23));
        scannear.setPreferredSize(new java.awt.Dimension(135, 23));
        scannear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scannearActionPerformed(evt);
            }
        });
        getContentPane().add(scannear);
        scannear.setBounds(210, 610, 140, 23);

        idMiniBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ploximo/Imagens/identidademini.png"))); // NOI18N
        idMiniBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMiniBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(idMiniBotao);
        idMiniBotao.setBounds(10, 490, 100, 60);

        permMiniBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ploximo/Imagens/permissaomini.png"))); // NOI18N
        permMiniBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permMiniBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(permMiniBotao);
        permMiniBotao.setBounds(120, 430, 80, 110);

        passMiniBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ploximo/Imagens/passaportemini.png"))); // NOI18N
        passMiniBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passMiniBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(passMiniBotao);
        passMiniBotao.setBounds(250, 460, 80, 110);

        regrasMiniBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ploximo/Imagens/regrasmini.png"))); // NOI18N
        regrasMiniBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regrasMiniBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(regrasMiniBotao);
        regrasMiniBotao.setBounds(110, 560, 90, 110);

        ploximoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ploximoBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(ploximoBotao);
        ploximoBotao.setBounds(300, 120, 150, 100);

        pessoaBotao.setContentAreaFilled(false);
        pessoaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(pessoaBotao);
        pessoaBotao.setBounds(90, 280, 160, 170);

        pesoBotao.setContentAreaFilled(false);
        pesoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(pesoBotao);
        pesoBotao.setBounds(230, 650, 130, 20);

        dataBotao.setToolTipText("");
        dataBotao.setContentAreaFilled(false);
        dataBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(dataBotao);
        dataBotao.setBounds(0, 650, 120, 20);

        aprovarBotao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aprovarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprovarBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(aprovarBotao);
        aprovarBotao.setBounds(490, 220, 170, 50);

        negarBotao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        negarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negarBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(negarBotao);
        negarBotao.setBounds(780, 220, 130, 50);

        ataqueLabel.setToolTipText("");
        getContentPane().add(ataqueLabel);
        ataqueLabel.setBounds(690, 10, 510, 190);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ploximo/Imagens/Jogo fundo.png"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 1200, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void negarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negarBotaoActionPerformed
        if (temPessoa) {
            jogoController.calcularPontuacao(this,this.pontos);
        
        System.out.println("NomeJogador:" + pontos.getNome());
        System.out.println("Pontuação:" + pontos.getPontos());
        temPessoa = false;
            try {
                jogoController.negarImigrante(this);
            } catch (Throwable ex) {
                Logger.getLogger(JogoTela.class.getName()).log(Level.SEVERE,
                                                                    null, ex);
            }
            
            passPainel.setVisible(false);
            idPainel.setVisible(false);
            permPainel.setVisible(false);
            passMiniBotao.setVisible(false);
            idMiniBotao.setVisible(false);
            permMiniBotao.setVisible(false);
            pesoBotao.setVisible(false);  
            pessoaBotao.setVisible(false);
        }
    }//GEN-LAST:event_negarBotaoActionPerformed

    private void idMiniBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMiniBotaoActionPerformed
        jogoController.togglePainel(idPainel);
        prioridadeExibicao(idPainel);
    }//GEN-LAST:event_idMiniBotaoActionPerformed

    private void regrasMiniBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regrasMiniBotaoActionPerformed
        jogoController.togglePainel(regrasPainel);
         prioridadeExibicao(regrasPainel);
    }//GEN-LAST:event_regrasMiniBotaoActionPerformed

    private void permMiniBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permMiniBotaoActionPerformed
        jogoController.togglePainel(permPainel);
        prioridadeExibicao(permPainel);
    }//GEN-LAST:event_permMiniBotaoActionPerformed

    private void passMiniBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passMiniBotaoActionPerformed
        jogoController.togglePainel(passPainel);
        prioridadeExibicao(passPainel);
    }//GEN-LAST:event_passMiniBotaoActionPerformed

    private void pesoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoBotaoActionPerformed
        jogoController.limitarCliques(pesoBotao, "peso");
    }//GEN-LAST:event_pesoBotaoActionPerformed
    
    private void idAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAltActionPerformed
        jogoController.limitarCliques(idAlt, "altura");
        prioridadeExibicao(idPainel);
    }//GEN-LAST:event_idAltActionPerformed

    private void passaporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passaporteMouseClicked
    }//GEN-LAST:event_passaporteMouseClicked

    private void passFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFotoActionPerformed
        prioridadeExibicao(passPainel);
    }//GEN-LAST:event_passFotoActionPerformed

    private void permPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permPesoActionPerformed
        jogoController.limitarCliques(permPeso, "peso");
        prioridadeExibicao(permPainel);
    }//GEN-LAST:event_permPesoActionPerformed

    private void passCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passCodActionPerformed
        jogoController.limitarCliques(passCod, "codigo do passaporte");
        prioridadeExibicao(passPainel);
    }//GEN-LAST:event_passCodActionPerformed

    private void idPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPesoActionPerformed
        jogoController.limitarCliques(idPeso, "peso");
        prioridadeExibicao(idPainel);
    }//GEN-LAST:event_idPesoActionPerformed

    private void idNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNomeActionPerformed
        jogoController.limitarCliques(idNome, "nome");
        prioridadeExibicao(idPainel);
    }//GEN-LAST:event_idNomeActionPerformed

    private void idNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNascActionPerformed
        jogoController.limitarCliques(idNasc, "nascimento");
        prioridadeExibicao(idPainel);
    }//GEN-LAST:event_idNascActionPerformed

    private void passValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passValActionPerformed
        jogoController.limitarCliques(passVal, "validade");
        prioridadeExibicao(passPainel);
    }//GEN-LAST:event_passValActionPerformed

    private void passSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passSexoActionPerformed
        jogoController.limitarCliques(passSexo, "sexo");
        prioridadeExibicao(passPainel);
    }//GEN-LAST:event_passSexoActionPerformed

    private void passPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPaisActionPerformed
        jogoController.limitarCliques(passPais, "pais");
        prioridadeExibicao(passPainel);
    }//GEN-LAST:event_passPaisActionPerformed

    private void passNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passNascActionPerformed
        jogoController.limitarCliques(passNasc,"nascimento");
        prioridadeExibicao(passPainel);
    }//GEN-LAST:event_passNascActionPerformed

    private void permPassCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permPassCodActionPerformed
        jogoController.limitarCliques(permPassCod, "codigo do passaporte");
        prioridadeExibicao(permPainel);
    }//GEN-LAST:event_permPassCodActionPerformed

    private void permNacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permNacioActionPerformed
        jogoController.limitarCliques(permNacio, "pais");
        prioridadeExibicao(permPainel);
    }//GEN-LAST:event_permNacioActionPerformed

    private void permMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permMotivoActionPerformed
         jogoController.limitarCliques(permMotivo, "motivo");
         prioridadeExibicao(permPainel);
    }//GEN-LAST:event_permMotivoActionPerformed

    private void permAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permAltActionPerformed
        jogoController.limitarCliques(permAlt, "altura");
        prioridadeExibicao(permPainel);
    }//GEN-LAST:event_permAltActionPerformed

    private void permDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permDuracaoActionPerformed
        jogoController.limitarCliques(permDuracao, "duracao");
        prioridadeExibicao(permPainel);
    }//GEN-LAST:event_permDuracaoActionPerformed

    private void permNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permNomeActionPerformed
        jogoController.limitarCliques(permNome, "nome");
        prioridadeExibicao(permPainel);
    }//GEN-LAST:event_permNomeActionPerformed

    private void permValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permValActionPerformed
        jogoController.limitarCliques(permVal, "validade");
        prioridadeExibicao(permPainel);
    }//GEN-LAST:event_permValActionPerformed

    private void ploximoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ploximoBotaoActionPerformed
        if(!temPessoa){
            temPessoa = true;
            jogoController.chamarImigrante(this);
            passMiniBotao.setVisible(true);
            idMiniBotao.setVisible(true);
            permMiniBotao.setVisible(true);
            pesoBotao.setVisible(true); 
            pessoaBotao.setVisible(true);
        }
    }//GEN-LAST:event_ploximoBotaoActionPerformed

    private void regra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regra1ActionPerformed
    }//GEN-LAST:event_regra1ActionPerformed

    private void regra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regra3ActionPerformed
    }//GEN-LAST:event_regra3ActionPerformed

    private void passNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passNomeActionPerformed
        jogoController.limitarCliques(passNome, "nome");
    }//GEN-LAST:event_passNomeActionPerformed

    private void pessoaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaBotaoActionPerformed
    }//GEN-LAST:event_pessoaBotaoActionPerformed

    private void aprovarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprovarBotaoActionPerformed
            if (temPessoa) {
                jogoController.calcularPontuacao(this,this.pontos);
                temPessoa = false;   
            
                try {
                    jogoController.aprovarImigrante(this);
                } catch (Throwable ex) {
                    Logger.getLogger(JogoTela.class.getName()).log(Level.SEVERE,
                                                                        null, ex);
                }

                this.passPainel.setVisible(false);
                this.permPainel.setVisible(false);
                this.idPainel.setVisible(false);
                passMiniBotao.setVisible(false);
                idMiniBotao.setVisible(false);
                permMiniBotao.setVisible(false);
                pesoBotao.setVisible(false);  
                pessoaBotao.setVisible(false);
                if (pc.isTerrorista()) {
                   jogoController.fazerAtaqueTerrorista(this);
               }
        }
    }//GEN-LAST:event_aprovarBotaoActionPerformed

    private void idFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFotoActionPerformed
    }//GEN-LAST:event_idFotoActionPerformed

    private void dataBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBotaoActionPerformed
        jogoController.limitarCliques(dataBotao, "data atual");
    }//GEN-LAST:event_dataBotaoActionPerformed

    private void scannearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scannearActionPerformed
        jogoController.pesoCorreto(this);      
    }//GEN-LAST:event_scannearActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pontuacao p = new Pontuacao();
                new JogoTela(p).setVisible(true);
            }
        }); 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aprovarBotao;
    private javax.swing.JLabel ataqueLabel;
    private javax.swing.JLabel cronometroLabel;
    private javax.swing.JButton dataBotao;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton idAlt;
    private javax.swing.JButton idFoto;
    private javax.swing.JButton idMiniBotao;
    private javax.swing.JButton idNasc;
    private javax.swing.JButton idNome;
    private javax.swing.JLayeredPane idPainel;
    private javax.swing.JButton idPeso;
    private javax.swing.JLabel identidade;
    private javax.swing.JButton negarBotao;
    private javax.swing.JButton passCod;
    private javax.swing.JButton passFoto;
    private javax.swing.JButton passMiniBotao;
    private javax.swing.JButton passNasc;
    private javax.swing.JButton passNome;
    private javax.swing.JLayeredPane passPainel;
    private javax.swing.JButton passPais;
    private javax.swing.JButton passSexo;
    private javax.swing.JButton passVal;
    private javax.swing.JLabel passaporte;
    private javax.swing.JButton permAlt;
    private javax.swing.JButton permDuracao;
    private javax.swing.JButton permMiniBotao;
    private javax.swing.JButton permMotivo;
    private javax.swing.JButton permNacio;
    private javax.swing.JButton permNome;
    private javax.swing.JLayeredPane permPainel;
    private javax.swing.JButton permPassCod;
    private javax.swing.JButton permPeso;
    private javax.swing.JButton permVal;
    private javax.swing.JLabel permissao;
    private javax.swing.JButton pesoBotao;
    private javax.swing.JButton pessoaBotao;
    private javax.swing.JButton ploximoBotao;
    private javax.swing.JLabel pontuacaoLabel;
    private javax.swing.JButton regra1;
    private javax.swing.JButton regra2;
    private javax.swing.JButton regra3;
    private javax.swing.JButton regra4;
    private javax.swing.JLabel regras;
    private javax.swing.JButton regrasMiniBotao;
    private javax.swing.JLayeredPane regrasPainel;
    private javax.swing.JButton scannear;
    // End of variables declaration//GEN-END:variables

    private void iniciarMeusComponentes() {
        jogoController.iniciarMeusComponentes(this, fundo);
    }
    
    private void prioridadeExibicao(JLayeredPane painel) {
        Container jp = this.getContentPane();
        if(painel != passPainel){
            jp.setComponentZOrder(passPainel, 3);
            passPainel.setVisible(!passPainel.isVisible());
            passPainel.setVisible(!passPainel.isVisible());
        } 
        if(painel != permPainel){
            jp.setComponentZOrder(permPainel, 4);
            permPainel.setVisible(!permPainel.isVisible());
            permPainel.setVisible(!permPainel.isVisible());
        }
        if(painel!= idPainel){
            jp.setComponentZOrder(idPainel, 2);
            idPainel.setVisible(!idPainel.isVisible());
            idPainel.setVisible(!idPainel.isVisible());

        }
        if(painel!= regrasPainel){
            jp.setComponentZOrder(regrasPainel, 5);
            regrasPainel.setVisible(!regrasPainel.isVisible());
            regrasPainel.setVisible(!regrasPainel.isVisible());
        }
        jp.setComponentZOrder(painel, 1);
    }
    
    public Pessoa getImigrante() {
        return imigrante;
    }

    public void setImigrante(Pessoa imigrante) {
        this.imigrante = imigrante;
    }

    public JogoController getJogoController() {
        return jogoController;
    }

    public void setJogoController(JogoController jogoController) {
        this.jogoController = jogoController;
    }
    
    public PessoaController getPessoaController() {
        return pc;
    }

    public void setPc(PessoaController pc) {
        this.pc = pc;
    }

    public JLabel getFundo() {
        return fundo;
    }

    public void setFundo(JLabel fundo) {
        this.fundo = fundo;
    }

    public JButton getIdAlt() {
        return idAlt;
    }

    public void setIdAlt(JButton idAlt) {
        this.idAlt = idAlt;
    }

    public JButton getIdFoto() {
        return idFoto;
    }

    public void setIdFoto(JButton idFoto) {
        this.idFoto = idFoto;
    }

    public JButton getIdNasc() {
        return idNasc;
    }

    public void setIdNasc(JButton idNasc) {
        this.idNasc = idNasc;
    }

    public JButton getIdNome() {
        return idNome;
    }

    public void setIdNome(JButton idNome) {
        this.idNome = idNome;
    }

    public JButton getIdPeso() {
        return idPeso;
    }

    public void setIdPeso(JButton idPeso) {
        this.idPeso = idPeso;
    }

    public JButton getPassCid() {
        return passPais;
    }

    public void setPassCid(JButton passCid) {
        this.passPais = passCid;
    }

    public JButton getPassCod() {
        return passCod;
    }

    public void setPassCod(JButton passCod) {
        this.passCod = passCod;
    }

    public JButton getPassFoto() {
        return passFoto;
    }

    public void setPassFoto(JButton passFoto) {
        this.passFoto = passFoto;
    }

    public JButton getPassNasc() {
        return passNasc;
    }

    public void setPassNasc(JButton passNasc) {
        this.passNasc = passNasc;
    }

    public JButton getPassNome() {
        return passNome;
    }

    public void setPassNome(JButton passNome) {
        this.passNome = passNome;
    }

    public JButton getPassSexo() {
        return passSexo;
    }

    public void setPassSexo(JButton passSexo) {
        this.passSexo = passSexo;
    }

    public JButton getPassVal() {
        return passVal;
    }

    public void setPassVal(JButton passVal) {
        this.passVal = passVal;
    }

    public JButton getPermAlt() {
        return permAlt;
    }

    public void setPermAlt(JButton permAlt) {
        this.permAlt = permAlt;
    }

    public JButton getPermDuracao() {
        return permDuracao;
    }

    public void setPermDuracao(JButton permDuracao) {
        this.permDuracao = permDuracao;
    }

    public JButton getPermMotivo() {
        return permMotivo;
    }

    public void setPermMotivo(JButton permMotivo) {
        this.permMotivo = permMotivo;
    }

    public JButton getPermNacio() {
        return permNacio;
    }

    public void setPermNacio(JButton permNacio) {
        this.permNacio = permNacio;
    }

    public JButton getPermNome() {
        return permNome;
    }

    public void setPermNome(JButton permNome) {
        this.permNome = permNome;
    }

    public JLayeredPane getPermPainel() {
        return permPainel;
    }

    public void setPermPainel(JLayeredPane permPainel) {
        this.permPainel = permPainel;
    }

    public JButton getPermPassCod() {
        return permPassCod;
    }

    public void setPermPassCod(JButton permPassCod) {
        this.permPassCod = permPassCod;
    }

    public JButton getPermPeso() {
        return permPeso;
    }

    public void setPermPeso(JButton permPeso) {
        this.permPeso = permPeso;
    }

    public JButton getPermVal() {
        return permVal;
    }

    public void setPermVal(JButton permVal) {
        this.permVal = permVal;
    }

    public JButton getPesoBotao() {
        return pesoBotao;
    }

    public void setPesoBotao(JButton pesoBotao) {
        this.pesoBotao = pesoBotao;
    }

    public JButton getPessoaBotao() {
        return pessoaBotao;
    }

    public void setPessoaBotao(JButton pessoaBotao) {
        this.pessoaBotao = pessoaBotao;
    }

    public JLabel getAtaqueLabel() {
        return ataqueLabel;
    }

    public void setAtaqueLabel(JLabel ataqueLabel) {
        this.ataqueLabel = ataqueLabel;
    }

    public JButton getPloximoBotao() {
        return ploximoBotao;
    }

    public void setPloximoBotao(JButton ploximoBotao) {
        this.ploximoBotao = ploximoBotao;
    }
    
    public void fimDeDia(){
        jogoController.terminarDia(this, 0, pontos);
    }

    public JLabel getCronometroLabel() {
        return cronometroLabel;
    }

    public void setCronometroLabel(JLabel cronometroLabel) {
        this.cronometroLabel = cronometroLabel;
    }

    public JLabel getPontuacaoLabel() {
        return pontuacaoLabel;
    }

    public void setPontuacaoLabel(JLabel pontuacaoLabel) {
        this.pontuacaoLabel = pontuacaoLabel;
    }

    public Pontuacao getPontos() {
        return pontos;
    }

    public void setPontos(Pontuacao pontos) {
        this.pontos = pontos;
    }
}