/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ploximo.Views;

import java.io.IOException;
import java.util.ArrayList;
import ploximo.Models.Pessoa;
import ploximo.controle.JogoController;
import ploximo.controle.PessoaController;
import ploximo.controle.Pontuacao;

/**
 *
 * @author Luan
 */
public class MenuPrincipal extends javax.swing.JFrame {

    
    JogoController jogoController = new JogoController();
    Pontuacao pontos = new Pontuacao();        
    public MenuPrincipal() {
        initComponents();
        
        ArrayList botoes = new ArrayList<>();
        botoes.add(novoJogoBotao);
        botoes.add(highScoresBotao);
        botoes.add(sairBotao);
        jogoController.configurarBotoes(botoes);
        iniciarMesuComponentes();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        novoJogoBotao = new javax.swing.JButton();
        highScoresBotao = new javax.swing.JButton();
        sairBotao = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        novoJogoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoJogoBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(novoJogoBotao);
        novoJogoBotao.setBounds(440, 290, 310, 50);

        highScoresBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoresBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(highScoresBotao);
        highScoresBotao.setBounds(490, 400, 220, 50);

        sairBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(sairBotao);
        sairBotao.setBounds(550, 500, 90, 40);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ploximo/Imagens/menu.png"))); // NOI18N
        fundo.setText("jLabel1");
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 1200, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoJogoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoJogoBotaoActionPerformed
        jogoController.trocarDeTela(this, new JogoTela(pontos));          
    }//GEN-LAST:event_novoJogoBotaoActionPerformed

    private void sairBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBotaoActionPerformed
        jogoController.fecharTela(this);
    }//GEN-LAST:event_sairBotaoActionPerformed

    private void highScoresBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoresBotaoActionPerformed
        jogoController.trocarDeTela(this, new HighScores());
    }//GEN-LAST:event_highScoresBotaoActionPerformed

    /*
    * BUGS CONHECIDOS / TO DOs
    
    - sobreposição dos panels/documentos
    - ftos, nome, etc dando null
   
    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        PessoaController pc = new PessoaController();
        Pessoa pessoa = pc.gerar();
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JButton highScoresBotao;
    private javax.swing.JButton novoJogoBotao;
    private javax.swing.JButton sairBotao;
    // End of variables declaration//GEN-END:variables

    private void iniciarMesuComponentes() {
        jogoController.iniciarMeusComponentes(this, fundo);
    }
}
